version: 2.0

jobs:
  centos_build98:
    docker:
      - image: centos:7
    filters:
      branches:
        - only: stable
    working_directory: ~/gismo
    environment:
      MAKEFLAGS: -j4
    steps:
      - run:
          name: Install dependencies
          command: yum install -y git cmake make gcc-c++ #valgrind
      - checkout
      - run:
          name: Configure G+Smo on CentOS
          command: cmake . -DSITE="$CIRCLE_USERNAME-$CIRCLE_BRANCH [circleci98]" -DGISMO_INSOURCE_BUILD=ON -DGISMO_BUILD_UNITTESTS=ON -DCMAKE_CXX_STANDARD=98 -DGISMO_WITH_ONURBS=ON
      - run:
          name: Build and test G+Smo on CentOS
          command: ctest $MAKEFLAGS --output-on-failure -D ExperimentalStart -D ExperimentalConfigure -D ExperimentalBuild -D ExperimentalTest -D ExperimentalSubmit #-D ExperimentalMemCheck

  macos_build: #OS SEED plan!
    macos:
      xcode: "11.7.0"
    filters:
      branches:
        - only: stable
    working_directory: ~/gismo
    environment:
      MAKEFLAGS: -j4
    steps:
      - run:
          name: Install dependencies
          command: brew install cmake # git make clang libgcc #valgrind
      - checkout
      - run:
          name: Configure G+Smo on MacOS
          command: cmake . -DSITE="$CIRCLE_USERNAME-$CIRCLE_BRANCH [macos]" -DGISMO_INSOURCE_BUILD=ON -DGISMO_BUILD_UNITTESTS=ON -DGISMO_WITH_ONURBS=ON
      - run:
          name: Build and test G+Smo on MacOS
          command: ctest $MAKEFLAGS --output-on-failure -D ExperimentalStart -D ExperimentalConfigure -D ExperimentalBuild -D ExperimentalTest -D ExperimentalSubmit #-D ExperimentalMemCheck

#deployment:
#    working_directory: ~/deploy
#    docker:
#      - image: centos:7
#    steps:
#      - run:
#          name: Install dependencies
#          command: yum install -y git
#      - checkout
#      - run:
#          name: Deploy the code from CentOS
#          command:

workflows:
  version: 2
  build:
    jobs:
      - centos_build98
      - macos_build

#      - deployment:
#          requires:
#            - build
